### ISSUE TITLE
Änderung

### ISSUE THREAD

**Issue by Braandn** [tutRPi/Raspberry-Pi-Simple-Web-GPIO-GUI#1]
Wär es möglich einen Schalter für nur einen Pin auf der Seite darstellen zu lassen,
ich kenne mich mit NodeJS nicht aus und frage deshalb, weil ich bis jetzt noch kein besseres Web GPIO Layout im Internet gefunden habe als das und es mich sehr anspricht

**Comment by tutRPi** [comment]
Ja, natürlich. Einfach die Datei `views/index.jade` entsprechend umändern.
